### ISSUE TITLE
Wrong parameter index on multiple wheres

### ISSUE THREAD

**Issue by rick20** [glushkovds/phpclickhouse-laravel#18]
Hi,

I encountered an issue when trying to use multiple ```where```s.
The following query
```php
Sales::query()
  ->select([
      "lines",
      "month",
      "SUM(qty) AS amount",
  ])
  ->whereIn('product_id', [2])
  ->whereBetween('month', [$month['start'], $month['end']])
  ->toSql()
```
will produce:
```sql
select lines, month, SUM(qty) AS amount from "sales" where "product_id" in (:0) and "month" between :0 and :1
```

Each where will have parameter index begin from 0.
This will cause a product id is used as a first argument for month.
Is there any workaround for this particular issue?
Thanks.

**Comment by glushkovds** [comment]
Hi! 
Please, check out the test: https://github.com/glushkovds/phpclickhouse-laravel/blob/b9c2d19540da7d5278294ce82da58ac50b7797c9/tests/BaseTest.php#L34

I guess your `Sales` model isn't `PhpClickHouseLaravel\BaseModel`, because it didn't have a `query` method.

**Comment by aachekalov** [comment]
I guess the problem may occurs using (internally) `Illuminate\Database\Query\Builder` instead of `PhpClickHouseLaravel\Builder`

That's because in the [QueryGrammar.php](https://github.com/glushkovds/phpclickhouse-laravel/blob/b9c2d19540da7d5278294ce82da58ac50b7797c9/src/QueryGrammar.php#L15-L29) in case Where In: `:number` calculates in place, but in case Basic Where: does later over `#@?` stub.

@glushkovds Why don't you use `parameterize` from the parent class?
