### ISSUE TITLE
Problem with QueryGrammar::prepareParameters

### ISSUE THREAD

**Issue by xdendev** [glushkovds/phpclickhouse-laravel#30]
Hello, thanks for ur package. We integret CH very faster with ur help!
But i got problem with bindings, if we have many wheres[], bind pos :0 in last where will has incorrect value when use Eloquent Builder

Code:
```
$query = Log::query();

$query->where(function ($query)  use ($value) { 
  return $query
             ->orWhere('column1', 'like', '%test%')
             ->orWhere('column2', 'like', '%test%')
             ->orWhere('column3', 'like', '%test%')
             ->orWhere('column4', '=', 0);
});

// some scenario

$query->whereIn('column5', [4]);
```

Prepare:
 `select count(*) as aggregate from "logs" where ("column1" like :0 or "column2" like :1 or "column3" like :2 or "column4" = :3) and "logs"."column5" in (:0)`

Bindings:  
```
 0 => "%test%"
 1 => "%test%"
 2 => "%test%"
 3 => 0
 4 => "4"
```
Sql:
`
select count(*) as aggregate from "logs" where ("column1" like '%test%' or "column2" like '%test%' or "column3" like '%test%'  or "column4" = 0) and "logs"."column5" in ('%test%')  // not "4" (:4)
`

**Comment by aachekalov** [comment]
That's because [`compileWheres`](https://github.com/glushkovds/phpclickhouse-laravel/blob/master/src/QueryGrammar.php#L32C5-L35C6) function is used recursively in case of _Nested Where_. And internally braсkets `()` in where clause are represented by a Nested type.

I think it would be better to override `compileComponents` instead of `compileWheres`, so that parameters are substituted after the where clause has been completely compiled. Something like this:
```php
    /** @inheritDoc */
    protected function compileComponents(Builder $query)
    {
        $sql = parent::compileComponents($query);

        if (!empty($sql['wheres'])) {
            $sql['wheres'] = static::prepareParameters($sql['wheres']);
        }

        return $sql;
    }
```

**Comment by glushkovds** [comment]
Hi there,

Please, see the auto test, it passes:
https://github.com/glushkovds/phpclickhouse-laravel/blob/master/tests/BindingsTest.php

I guess you need to call `Log::select()` instead of `Log::query()`. Moreover, last static method doesn't exist.

Please provide a more detailed example if the problem still remains.
